/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

int *
count_1_svc(rpc_data *argp, struct svc_req *rqstp)
{
	FILE * secrets_file;
	static int num_count = 0;

	char buffer [100];
	strcpy(buffer, argp->content);
	printf("Received %s with length %lu\n", buffer, strlen(buffer));
	printf("Received %s with length %lu\n", argp->content, strlen(argp->content));

	num_count = 0;
	for( int i = 0; buffer[i] != '\0'; i++){
		// if C00L starts at the current index, skip ahead of it so the 0's
		// in C00L are not counted
		if( strstr(&buffer[i], "C00L") == &buffer[i] ){
			i = i + 3;
			continue;
		}
		// if the character is a digit, add it to the count
		if (isdigit(buffer[i])){
			num_count++;
		}
	}

	printf("Number of digits: %d\n", num_count);

	// write the number of digits and the full string to file (append only)
	if((secrets_file = fopen("secrets.out", "a")) == NULL){
		printf("Could not open secrets.out file!\n");
		exit(1);
	}

	fprintf(secrets_file, "%d - %s\n", num_count, buffer);
	fclose(secrets_file);


	return &num_count;
}
